name: ESLint Check
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Updated to the latest version
    - name: Use Node.js 16
      uses: actions/setup-node@v4 # Updated to the latest version
      with:
        node-version: '16' # Specify Node.js version 16
    - name: Install Dependencies
      run: npm install
    - name: Run ESLint
      run: npx eslint .